### ISSUE TITLE
Failed calling extension of Object

### ISSUE THREAD

**Issue by ampersanda** [Tensegritics/ClojureDart#63] opened 2022-05-13 16:15 UTC
I tried to implement `hive_flutter` inside my project and it needs to be initialized using `Hive.initFlutter()` which `initFlutter()` is an extension inside the package. 

But instead of calling the `Hive.initFlutter()` directly, it seems that generated dart always casting it back to `dynamic` so calling extension will fail

core from my project

```clj
(defn main ^:async []
  (let [local hive/Hive]
    (.initFlutter local)))
```

and generated dart file be

```dart
dc.dynamic main(){
final h_hive.HiveInterface local$1=h_hive_flutter.Hive;
(local$1 as dc.dynamic).initFlutter(); // fails here because of casting
}
```

the extension from package
```dart
part of hive_flutter;

/// Flutter extensions for Hive.
extension HiveX on HiveInterface {
  /// Initializes Hive with the path from [getApplicationDocumentsDirectory].
  ///
  /// You can provide a [subDir] where the boxes should be stored.
  Future<void> initFlutter([String? subDir]) async {
    WidgetsFlutterBinding.ensureInitialized();
    if (kIsWeb) return;

    var appDir = await getApplicationDocumentsDirectory();
    init(path_helper.join(appDir.path, subDir));
  }
}
```

CLI error

```
Restarted application in 871ms.
Error: NoSuchMethodError: 'initFlutter'
Dynamic call of null.
Receiver: Instance of 'HiveImpl'
Arguments: []
    at Object.throw_ [as throw] (http://localhost:61884/dart_sdk.js:5063:11)
    at Object.defaultNoSuchMethod (http://localhost:61884/dart_sdk.js:5497:15)
    at hive_impl.HiveImpl.new.noSuchMethod (http://localhost:61884/dart_sdk.js:6588:19)
    at Object.noSuchMethod (http://localhost:61884/dart_sdk.js:5494:30)
    at callNSM (http://localhost:61884/dart_sdk.js:5233:19)
    at Object._checkAndCall (http://localhost:61884/dart_sdk.js:5235:27)
    at Object.callMethod (http://localhost:61884/dart_sdk.js:5313:17)
    at Object.dsend (http://localhost:61884/dart_sdk.js:5316:17)
    at main$ (http://localhost:61884/packages/bgbtapp/cljd-out/bgbt/main.dart.lib.js:87:10)
    at main (http://localhost:61884/web_entrypoint.dart.lib.js:36:29)
    at main.next (<anonymous>)
    at http://localhost:61884/dart_sdk.js:40192:33
    at _RootZone.runUnary (http://localhost:61884/dart_sdk.js:40062:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:61884/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:61884/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:61884/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:61884/dart_sdk.js:35437:23)
    at http://localhost:61884/dart_sdk.js:34617:46
    at _RootZone.runUnary (http://localhost:61884/dart_sdk.js:40062:59)
    at _FutureListener.then.handleValue (http://localhost:61884/dart_sdk.js:34983:29)
    at handleValueCallback (http://localhost:61884/dart_sdk.js:35551:49)
    at Function._propagateToListeners (http://localhost:61884/dart_sdk.js:35589:17)
    at _Future.new.[_completeWithValue] (http://localhost:61884/dart_sdk.js:35437:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61884/dart_sdk.js:35458:35)
    at Object._microtaskLoop (http://localhost:61884/dart_sdk.js:40330:13)
dk.js:40336:13)crotaskLoop (http://localhost:61884/dart_s
    at http://localhost:61884/dart_sdk.js:35811:9
No extension of protocol IWithMeta found for type HiveImpl.
```

I tried removing manually `as dc.dynamic` in generated file and works well. Is there any way to force type to be not casted to `dynamic`?

**Comment by cgrand** [comment] 2022-05-13 22:54
Sadly the only answer is to reimplement the code of the extension. Dupe of #10

**Closed by cgrand** 2022-05-13 22:54 UTC
